# Generated by Django 5.0.4 on 2024-05-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_course_teacher_alter_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
