# Generated by Django 5.0.6 on 2024-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(default='https://example.com/default-image.jpg', max_length=400),
        ),
    ]
