# Generated by Django 5.0.4 on 2024-05-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_usercourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
