# Generated by Django 5.0.6 on 2024-05-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_category_image_url_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.CharField(default='images/art.jpg', max_length=255),
        ),
    ]
